---
- name: Install openBCE addons
  hosts: localhost
  vars_files:
    - ../bce.yaml
  tasks:
    - name: Generate OVN Configuration
      template: src=templates/ovn/ovn-config.yaml.j2 dest=../kustomize/ovn/ovnkube/ovn-config.yaml
    
    - name: Install OVN-Kubernetes
      shell: ../sbin/kubectl apply --kubeconfig {{ playbook_dir }}/config/kube.config -k ../kustomize/ovn

#    - name: Install Calico
#      shell: ../sbin/kubectl apply --kubeconfig {{ playbook_dir }}/config/kube.config -f {{ playbook_dir }}/templates/calico.yaml

    - name: Generate Metallb configuration
      template: src=templates/metallb-config.yaml.j2 dest=../kustomize/metallb/metallb-config.yaml

    - name: Install Metallb
      shell: ../sbin/kubectl apply --kubeconfig {{ playbook_dir }}/config/kube.config -k ../kustomize/metallb

