---
- name: Install openBCE master
  hosts: masters
  vars_files:
    - ../bce.yaml
  tasks:
    - name: Uninstall Old Kubernetes
      shell: kubeadm reset --force

    - name: Pull Images
      shell: kubeadm config images pull  \
          --kubernetes-version={{ k8s_version }} \
          --image-repository={{ image_repository }}

    - name: Install Kubernetes Master
      shell: kubeadm init \
        --kubernetes-version={{ k8s_version }} \
        --image-repository={{ image_repository }} \
        --pod-network-cidr={{ pod_cidr }} \
        --apiserver-advertise-address={{ inventory_hostname }} \
        --service-cidr={{ service_cidr }}

- name: Fetch openBCE master config
  hosts: masters[0]
  vars_files:
    - ../bce.yaml
  tasks:
    - name: Generate Worker tokens
      shell: kubeadm token create $(kubeadm token generate) --print-join-command > /etc/kubernetes/worker.conf

    - name: Fetch worker join command
      fetch: src=/etc/kubernetes/worker.conf dest={{ playbook_dir }}/config/worker-join.conf flat=yes

    - name: Fetch kubeconfig
      fetch: src=/etc/kubernetes/admin.conf dest={{ playbook_dir }}/config/kube.config flat=yes


