apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dhcp
  name: dhcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhcp
  template:
    metadata:
      labels:
        app: dhcp
    spec:
      containers:
      - image: openbce/dnsmasq:v0.1
        name: dnsmasq
        ports:
        - containerPort: 67
          protocol: UDP
        - containerPort: 68
          protocol: UDP
        - containerPort: 69
          protocol: UDP
        resources: 
          limits:
            cpu: 0.5
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
          - name: dhcp-config
            mountPath: /etc/dnsmasq.conf
            subPath: dnsmasp.config
          - name: tftp-dir 
            mountPath: /var/lib/tftpboot
          - name: log-dir 
            mountPath: /var/log
      volumes:
        - name: dhcp-config
          configMap:
            name: dhcp-config
        - name: tftp-dir
          hostPath:
            path: /home/klausm/bce/bce-v0.1.0/tftp
        - name: log-dir
          hostPath:
            path: /home/klausm/bce/bce-v0.1.0/log
