apiVersion: v1
kind: Service
metadata:
  labels:
    app: ironic
  name: ironic-svc
spec:
  ports:
  - name: ironic-api
    port: 6385
    targetPort: 6385
  - name: ironic-inspector
    port: 5050
    targetPort: 5050
  selector:
    app: ironic
  type: ClusterIP
