apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ironic
  name: ironic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ironic
  template:
    metadata:
      labels:
        app: ironic
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
      - name: genconf
        image: openbce/ironic-init:v0.1.0
        command: ["/opt/ironic/scripts/init-ironic-conf.sh"] 
        securityContext:
          privileged: true
        envFrom:
          - configMapRef:
              name: mariadb-secret
        volumeMounts:
          - name: ironic-conf
            mountPath: /etc/ironic
          - name: ironic-scripts
            mountPath: /opt/ironic/scripts
          - name: ironic-images
            mountPath: /opt/ironic/images
      containers:
      - image: openbce/ironic:20.2.0
        name: ironic
        command: ["/usr/local/bin/ironic"]
        securityContext:
          privileged: true
        resources: 
          limits:
            cpu: 2
        volumeMounts:
          - name: ironic-conf
            mountPath: /etc/ironic
          - name: ironic-images
            mountPath: /opt/ironic/images
      - image: openbce/ironic-inspector:10.12.0
        name: ironic-inspector
        command: ["/usr/local/bin/ironic-inspector"]
        resources: 
          limits:
            cpu: 2
        volumeMounts:
          - name: ironic-conf
            mountPath: /etc/ironic
          - name: ironic-images
            mountPath: /opt/ironic/images
      volumes:
      - name: ironic-conf 
        emptyDir: {}
      - name: ironic-scripts
        hostPath:
          path: /home/klausm/bce/installer/scripts/ironic
      - name: ironic-images
        hostPath:
          path: /home/klausm/bce/installer/work/ironic/images
