apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-services
subjects:
  - kind: ServiceAccount
    name: default
    namespace: baremetal-operator-system
roleRef:
  kind: Role 
  name: service-reader 
  apiGroup: rbac.authorization.k8s.io
