apiVersion: v1
kind: Service
metadata:
  labels:
    app: ipxe
  name: ipxe-svc
  namespace: default
spec:
  ports:
  - name: dhcp-67
    port: 67
    protocol: UDP
    targetPort: 67
  - name: dhcp-68
    port: 68
    protocol: UDP
    targetPort: 68
  - name: tftp
    port: 69
    protocol: UDP
    targetPort: 69
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: ipxe
  type: LoadBalancer
