apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ipxe
  name: ipxe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipxe
  template:
    metadata:
      labels:
        app: ipxe
    spec:
      containers:
      - image: httpd:2.4
        name: httpd
        ports:
        - containerPort: 8080
        resources: 
          limits:
            cpu: 0.5
        volumeMounts:
          - name: httpd-dir 
            mountPath: /usr/local/apache2/htdocs
          - name: httpd-config
            mountPath: /usr/local/apache2/conf/httpd.conf
            subPath: httpd.conf
      - image: openbce/dnsmasq:v0.1
        name: dnsmasq
        ports:
        - containerPort: 67
          protocol: UDP
        - containerPort: 68
          protocol: UDP
        - containerPort: 69
          protocol: UDP
        resources: 
          limits:
            cpu: 0.5
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
          - name: dnsmasq-config
            mountPath: /etc/dnsmasq.conf
            subPath: dnsmasq.conf
          - name: tftp-dir 
            mountPath: /var/lib/tftpboot
      volumes:
        - name: dnsmasq-config
          configMap:
            name: dnsmasq-config
        - name: httpd-config
          configMap:
            name: httpd-config
        - name: tftp-dir
          hostPath:
            path: /home/klausm/bce/installer/work/ironic/images/tftpboot
        - name: httpd-dir
          hostPath:
            path: /home/klausm/bce/installer/work/ironic/images/httpboot

