apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: dnsmasq-config
    files:
      - dnsmasq.conf
  - name: httpd-config
    files:
      - httpd.conf
resources:
  - ipxe.yaml
  - ipxe-svc.yaml
