apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-secret
  labels:
    app: mariadb
data:
  MARIADB_DATABASE: ironic
  MARIADB_USER: ironic
  MARIADB_PASSWORD: Letmein123
  MARIADB_ROOT_PASSWORD: Letmein123
